### ISSUE TITLE
simpleCtx distributes wrongly

### ISSUE THREAD

**Issue by ymndoseijin** [InKryption/comath#5]
```zig
try util.testing.expectEqual(6 - 3 + 4 + 2, comath.eval("6*1-3*1+4*1+2", simpleCtx({}), .{}));
```
This fails, because the right expression evaluates to -3 (6-3-4-2 instead of 6-3+4+2). It seems to happen when multiplying, like the negative sign carries over from -3 to the other numbers.

**Comment by InKryption** [comment]
The issue actually appears to be in parsing specifically. Currently the expression `6*1-3*1+4*1+2`, with the usual precedences (`*` > `+`, `-`), parses as:
`(6 * 1) - ((3 * 1) + ((4 * 1) + 2))`
where it should parse as:
`(((6 * 1) - (3 * 1)) + (4 * 1)) + 2`

I will have to do some reworking.
